/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7e5e10da-61e9-41c0-a8cf-7ec18b49e3ce",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_881RYcqFQ",
    "aws_user_pools_web_client_id": "3b2slo8antk7a1c561j6qd03j5",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "deceaseDetection",
            "endpoint": "https://jwpj70crj0.execute-api.us-east-1.amazonaws.com/plantdoc",
            "region": "us-east-1"
        },
        {
            "name": "UsersCRUD",
            "endpoint": "https://qsmz2oly4e.execute-api.us-east-1.amazonaws.com/plantdoc",
            "region": "us-east-1"
        },
        {
            "name": "hardware",
            "endpoint": "https://sld4v54bbg.execute-api.us-east-1.amazonaws.com/plantdoc",
            "region": "us-east-1"
        },
        {
            "name": "plants",
            "endpoint": "https://zzykxcow90.execute-api.us-east-1.amazonaws.com/plantdoc",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Plants-plantdoc",
            "region": "us-east-1"
        },
        {
            "tableName": "Users-plantdoc",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
