/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7e5e10da-61e9-41c0-a8cf-7ec18b49e3ce",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_881RYcqFQ",
    "aws_user_pools_web_client_id": "3b2slo8antk7a1c561j6qd03j5",
    "oauth": {}
};


export default awsmobile;
